name: build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ linux.amd64, linux.arm64, windows.amd64 ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: ui
        run: |
          cd ui
          npm install
          npm run build
          mv dist ../assets
          cd ..
      - name: build
        env:
          target: ${{ matrix.target }}
        run: |
          os=$(echo $target | awk -F. '{print $1}')
          arch=$(echo $target | awk -F. '{print $2}')
          ./build.sh $os $arch
